//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mvc_posEntities : DbContext
    {
        public mvc_posEntities()
            : base("name=mvc_posEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblcustomer> tblcustomers { get; set; }
        public virtual DbSet<tblinvoice> tblinvoices { get; set; }
        public virtual DbSet<tblproduct> tblproducts { get; set; }
        public virtual DbSet<tblproductcategory> tblproductcategories { get; set; }
        public virtual DbSet<tblproductunit> tblproductunits { get; set; }
        public virtual DbSet<tblpurchaseorder> tblpurchaseorders { get; set; }
        public virtual DbSet<tblreceiveproduct> tblreceiveproducts { get; set; }
        public virtual DbSet<tblsale> tblsales { get; set; }
        public virtual DbSet<tblsupplier> tblsuppliers { get; set; }
        public virtual DbSet<tbluser> tblusers { get; set; }
    }
}
