//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

namespace MVCproject.Models
{
 
    
    public partial class mvc_pos_conn : DbContext
    {

        public DbSet<tblcustomer> tblcustomers { get; set; }
        public DbSet<tblproductcategory> tblproductcategorys { get; set; }
        public DbSet<tblinvoice> tblinvoices { get; set; }
        public DbSet<tblproduct> tblproducts { get; set; }
        
        public DbSet<tblproductunit> tblproductunits { get; set; }
        public DbSet<tblpurchaseorder> tblpurchaseorders { get; set; }
        public DbSet<tblreceiveproduct> tblreceiveproducts { get; set; }
        public DbSet<tblsale> tblsales { get; set; }
        public DbSet<tblsupplier> tblsuppliers { get; set; }
        public DbSet<tbluser> tblusers { get; set; }

        public mvc_pos_conn()
                  : base("mvc_pos_conn")
        {
            Database.CreateIfNotExists();
        }

       

    }
}
