//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcustomer
    {
        public int @int { get; set; }
        public Nullable<decimal> customer_id { get; set; }
        public string customer_code { get; set; }
        public string customer_name { get; set; }
        public string contact { get; set; }
        public string address { get; set; }
        public Nullable<int> flag { get; set; }
    }
}
