//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblinvoice
    {
        public int id { get; set; }
        public decimal invoice_id { get; set; }
        public Nullable<decimal> customer_id { get; set; }
        public Nullable<decimal> payment_type { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public Nullable<decimal> amount_tendered { get; set; }
        public string bank_account_name { get; set; }
        public string bank_account_number { get; set; }
        public string date_recorded { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public Nullable<int> flag { get; set; }
    }
}
