//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCproject.Models
{

    
    public partial class tblreceiveproduct
    {
        public int id { get; set; }
        public string receive_product_id { get; set; }
        public string product_id { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public Nullable<decimal> supplier_id { get; set; }
        public Nullable<decimal> received_date { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public string flag { get; set; }
    }
}
