//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVCproject.Models
{

    
    public partial class tbluser
    {
        [Key]
        public int id { get; set; }
        public Nullable<decimal> user_id { get; set; }

        [DisplayName("User Name")]
        public string user_name { get; set; }
        public string password { get; set; }

        [DisplayName("Full Name")]
        public string fullname { get; set; }

        [DisplayName("Designation")]
        public string designation { get; set; }

        [DisplayName("Role")]
        public string role { get; set; }
        public Nullable<int> account_type { get; set; }
        public string flag { get; set; }

        [DisplayName("Email")]
        public string email_id { get; set; }
        
    }
}
