//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproductunit
    {
        public int id { get; set; }
        public decimal unit_id { get; set; }
        public string unit_name { get; set; }
    }
}
