//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblpurchaseorder
    {
        public int id { get; set; }
        public Nullable<decimal> purchase_order_id { get; set; }
        public Nullable<decimal> product_id { get; set; }
        public Nullable<decimal> quantity { get; set; }
        public Nullable<decimal> unit_price { get; set; }
        public Nullable<decimal> sub_total { get; set; }
        public Nullable<decimal> supplier_id { get; set; }
        public string order_date { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public Nullable<int> order_status { get; set; }
        public Nullable<int> flag { get; set; }
    }
}
