//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblproductcategory
    {
        public int id { get; set; }
        public Nullable<decimal> category_id { get; set; }
        public string category_name { get; set; }
        public string flag { get; set; }
    }
}
