//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblsupplier
    {
        public int id { get; set; }
        public Nullable<decimal> supplier_int { get; set; }
        public string supplier_code { get; set; }
        public string supplier_name { get; set; }
        public string supplier_contact { get; set; }
        public string supplier_address { get; set; }
        public byte[] supplier_email { get; set; }
        public Nullable<int> flag { get; set; }
    }
}
